name: Activity Log To Nexus

on:
  push:
    branches:
      - main

jobs:
  activity-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install node-fetch@2

    - name: Get user email
      id: get-email
      run: |
        email=$(git log -1 --pretty=format:'%ae')
        echo "email=$email" >> $GITHUB_ENV

    - name: Send data to nexus
      run: |
        node <<EOF
        const fetch = require('node-fetch');

        async function sendData() {
          const data = {
            action_item_id: "web_performance",
            activity_type_id: "code_push",
            github_email: process.env.email || "Unknown"
          };
          
          console.log('Sending data to Nexus:', data);

          const response = await fetch('https://nexus.theseniordev.com/user-activities', {
            method: 'POST',
            headers: { 
                'Content-Type': 'application/json',
                'x-api-key': 'jofJjEpTki'
            },
            body: JSON.stringify(data)
          });

          if (!response.ok) {
            console.error('Failed to send data:', response.statusText);
            process.exit(1);
          } else {
            console.log('Data sent successfully:', await response.json());
          }
        }

        sendData().catch(err => {
          console.error('Error sending data:', err);
          process.exit(1);
        });
        EOF
      env:
        NODE_OPTIONS: '--unhandled-rejections=strict'
        email: ${{ env.email }}
